/* ============================================================
   명동미래셀의원 · 언어팩
   ------------------------------------------------------------
   한국어가 원본입니다. 여기에 없는 문구는 한국어가 그대로 나옵니다.

   번역할 때 지켜 주십시오
   · 의료 문구는 과장하지 않습니다. 원문보다 더 좋게 옮기지 마십시오.
     ("도움이 됩니다"를 "치료됩니다"로 옮기는 식은 의료광고 규정 위반입니다.)
   · 진료 분야 상세 본문은 아직 한국어만 있습니다.
     검수된 번역이 준비되는 대로 svc.<키>.body 로 채우면 됩니다.
   · 대표자 성함은 로마자 표기(Park Jong-yun)로만 적었습니다.
     원장님께서 쓰시는 한자/가타카나 표기가 확인되면 바꿔 주십시오.
   ============================================================ */
window.MIRAE_LANGS = {

/* ══════════════════ 한국어 (원본) ══════════════════ */
ko: { name: "한국어", short: "KO", htmlLang: "ko", s: {} },

/* ══════════════════ English ══════════════════ */
en: { name: "English", short: "EN", htmlLang: "en", s: {
  "site.name": "Myeongdong Mirae Cell Clinic",
  "site.addr": "Myeongdong Mirae Cell Clinic, 7F, 123 Toegye-ro, Jung-gu, Seoul, Korea",
  "site.addr.short": "7F, 123 Toegye-ro, Jung-gu, Seoul",

  "nav.about": "About", "nav.services": "Treatments", "nav.community": "Community", "nav.contact": "Contact",
  "nav.about.intro": "About · Greeting", "nav.about.greeting": "Greeting",
  "nav.about.doctor": "Our Doctor", "nav.about.values": "Our Approach",
  "nav.about.location": "Directions", "nav.about.map": "Location & Map", "nav.about.transport": "Public Transport",
  "nav.community.notice": "Notices & News", "nav.community.list": "Notices", "nav.community.video": "YouTube",
  "nav.community.gallery": "Gallery", "nav.community.galleryItem": "Clinic Gallery",
  "nav.community.faq": "FAQ", "nav.community.faqItem": "FAQ",
  "nav.contact.inquiry": "Contact Us", "nav.contact.form": "Inquiry Form", "nav.contact.email": "Email Us",
  "nav.contact.reserve": "Appointments", "nav.contact.online": "Book Online", "nav.contact.phone": "Call 02-776-8768",
  "nav.cta": "Book a Visit", "nav.menu": "Open menu",

  "footer.services": "Treatments", "footer.quick": "Quick Links",
  "footer.reserve": "Book a Visit", "footer.contact": "Contact Us", "footer.location": "Directions",
  "footer.notice": "Notices & News", "footer.faq": "FAQ",
  "footer.ceoline": "Representative: Park Jong-yun · Tel",
  "footer.rights": "Myeongdong Mirae Cell Clinic. All rights reserved.",
  "footer.privacy": "Privacy Policy",
  "footer.compliance": "The content on this site complies with Korean medical advertising review standards.",
  "footer.langnote": "This page is a translation for your convenience. The Korean version prevails.",
  "quick.call": "Call us", "quick.reserve": "Book a visit",

  "svc.stemcell": "Stem Cell",
  "svc.stemcell.desc": "Your own cells, for your own body. Regenerative cells are separated from your own fat and blood, activated, and applied again.",
  "svc.derma": "Dermatology",
  "svc.derma.desc": "We don't only talk about what improves. How much, for how long, and what the risks are — we tell you all of it.",
  "svc.plastic": "Plastic Surgery",
  "svc.plastic.desc": "The reason someone looks older differs from person to person. We start by finding that reason.",
  "svc.urology": "Urology",
  "svc.urology.desc": "It is not rare — most people go through it. The harder it is to talk about, the more it begins with an accurate examination.",
  "svc.esthetic": "Aesthetics",
  "svc.esthetic.desc": "The procedure takes an hour; recovery takes weeks. We stay with you through those weeks.",
  "svc.toenail": "Ingrown Toenail",
  "svc.toenail.desc": "A big toe that hurts with every step is not something to put up with. In the early stages it can improve without removing the nail.",
  "svc.scalp": "Scalp Care",
  "svc.scalp.desc": "A programme that clears flakes and excess oil, releases a tight scalp, and carries the care through to the face.",
  "svc.lymph": "Lymphatic Care",
  "svc.lymph.desc": "Swelling relief · circulation care · condition care during recovery. A gentle programme that supports lymphatic flow.",
  "svc.worldtour": "World Tour",
  "svc.worldtour.desc": "A medical tour programme for visitors from Korea and from abroad.",
  "svc.quantum": "Quantum Care",
  "svc.quantum.desc": "Cells have batteries too. A supportive care programme that uses light and energy to help the body's own recovery.",
  "svc.konly.h": "The detail below is in Korean only.",
  "page.konly.h": "This page is available in Korean only for now.",
  "gal.close": "Close", "gal.prev": "Previous photo", "gal.next": "Next photo",
  "page.konly.p": "A reviewed English version is being prepared. Please write to us in English — we will answer you directly.",
  "svc.konly.p": "A reviewed English version of this treatment page is being prepared. In the meantime, please contact us in English and we will answer you directly.",

  "home.h1": "Care that begins at the cell,<br>for a healthier future",
  "home.p": "Your own health and beauty, renewed in the time of the cell.<br>Premium urology, plastic surgery and dermatology care<br>grounded in stem cell medicine — Myeongdong Mirae Cell Clinic.",
  "home.btn1": "Book a Visit", "home.btn2": "See Our Treatments",
  "home.info.tel": "Consultations", "home.info.loc": "Directions", "home.info.email": "Email",
  "home.prog.h2": "Our Treatments",
  "home.prog.p": "From stem cell care grounded in regenerative medicine to dermatology, plastic surgery and aesthetics — find the programme that fits you.",
  "home.c.stemcell": "Stem cell care using blood (PRP·PRF), fat, bone marrow and cord blood",
  "home.c.derma": "Exosomes, lifting, laser toning, skin boosters, fillers and botulinum",
  "home.c.plastic": "Eyes · nose · breast, hair transplant, upper/lower blepharoplasty, lifting, women's surgery",
  "home.c.urology": "Prostate conditions, men's surgery, sexual function (opens our dedicated site)",
  "home.c.esthetic": "Face and full-body care, medical massage",
  "home.c.scalp": "Scalp Care · Ingrown Toenail",
  "home.c.scalp.d": "Scalp care programmes and ingrown toenail treatment",
  "home.c.lymph": "Lymphatic circulation care that helps relieve swelling",
  "home.c.quantum": "Quantum Care",
  "home.c.quantum.d": "Quantum supportive care · World Tour programme",
  "home.more": "Read more →",
  "home.about.h2": "Honest medicine that begins<br>at the source of life — the cell",
  "home.about.p1": "Myeongdong Mirae Cell Clinic is grounded in regenerative and preventive medicine, and aims for care tailored to each patient's own condition.",
  "home.about.p2": "In the heart of Myeongdong, Seoul, we bring together stem cell care, dermatology and plastic surgery, aesthetics and quantum supportive care.",
  "home.about.btn": "About the Clinic",
  "home.news.h2": "Notices · News", "home.news.btn": "See All News",
  "home.news.b1": "Notice", "home.news.b2": "Info", "home.news.b3": "News",
  "home.news.1": "Our new website is now open.",
  "home.news.2": "Opening hours and appointment information (to be updated).",
  "home.news.3": "Consultation guide for stem cell programmes.",
  "home.rsv.h2": "Book your consultation today",
  "home.rsv.p": "One call or one click begins your consultation with our medical team.",
  "home.rsv.btn": "Book Online",

  "page.reserve.crumb": "HOME > Appointments",
  "page.reserve.h1": "Book a Visit",
  "page.reserve.p": "Leave the schedule you prefer and we will call you to confirm.",
  "page.contact.crumb": "HOME > Contact",
  "page.contact.h1": "Contact Us",
  "page.contact.p": "Leave your question and we will get back to you.",

  "form.name": "Name", "form.name.ph": "Your name",
  "form.phone": "Phone", "form.phone.ph": "010-0000-0000",
  "form.email": "Email", "form.email.ph": "example@email.com",
  "form.date": "Preferred date",
  "form.time": "Preferred time",
  "form.time.am": "Morning", "form.time.pm": "Afternoon", "form.time.any": "No preference",
  "form.topic.r": "Area of care", "form.topic.c": "Subject",
  "form.topic.etc": "Other",
  "form.msg.r": "Your message",
  "form.msg.r.ph": "Telling us your symptoms or questions helps us prepare for your consultation.",
  "form.msg.c": "Your message",
  "form.msg.c.ph": "Please write your question freely.",
  "form.note.r": "※ After we receive your request, our staff will call the number you leave during opening hours to confirm your appointment.",
  "form.note.c": "※ After we receive your message, our staff will reply to the contact you leave during opening hours.",
  "form.submit.r": "Request Appointment", "form.submit.c": "Send Inquiry",
  "form.urgent1": "If it is urgent, please call", "form.urgent2": ".",

  "consent.legend": "Consent to collection and use of personal data",
  "consent.req": "[Required]",
  "consent.opt": "[Optional]",
  "consent.req.r": "I consent to the collection and use of my personal data for appointment consultation.",
  "consent.req.r.d": "Items collected: name, contact number, preferred schedule · Purpose: confirming the appointment and contacting you · Retention: 3 years (You may refuse, but online booking will then not be possible.)",
  "consent.req.c": "I consent to the collection and use of my personal data in order to answer my inquiry.",
  "consent.req.c.d": "Items collected: name, contact number, email · Purpose: answering and guiding your inquiry · Retention: 3 years (You may refuse, but online inquiry will then not be possible.)",
  "consent.opt.r": "I consent to the collection and use of health-related (sensitive) data contained in my message.",
  "consent.opt.r.d": "You may submit without this consent; in that case your message is not stored and only your contact details are received.",
  "consent.opt.c": "I consent to the collection and use of health-related (sensitive) data contained in my inquiry.",
  "consent.opt.c.d": "You may submit without this consent; in that case your inquiry text is not stored and only your contact details are received.",
  "consent.link": "Read the full Privacy Policy",

  "contact.info.tel": "By phone", "contact.info.email": "By email", "contact.info.visit": "In person",

  "msg.name_invalid": "Please enter your name correctly.",
  "msg.phone_invalid": "Please check the format of your phone number (e.g. 010-0000-0000).",
  "msg.email_invalid": "Please check your email address.",
  "msg.date_invalid": "Please check the date you selected.",
  "msg.date_required": "Please select a preferred date.",
  "msg.message_required": "Please enter your message.",
  "msg.consent_required": "We can only accept your request once you consent to the collection and use of personal data.",
  "msg.captcha_failed": "The anti-spam check did not pass. Please try again in a moment.",
  "msg.rate_limited": "You have submitted several times in a short period. Please try again later or call us.",
  "msg.origin_not_allowed": "We could not verify where this request came from. Please open the website again and retry.",
  "msg.generic": "Something went wrong while submitting.",
  "msg.failhead": "Your request was not submitted.",
  "msg.failtail1": "If the problem continues, please call", "msg.failtail2": ".",
  "msg.sending": "Sending…",
  "msg.done.r": "Your appointment request has been received",
  "msg.done.c": "Your inquiry has been received",
  "msg.done.p": "We will check it and contact you at the number you left.<br>Requests received during opening hours are answered the same day; others on the next clinic day.",
  "msg.done.tel": "If it is urgent,"
}},

/* ══════════════════ 简体中文 ══════════════════ */
zh: { name: "简体中文", short: "中文", htmlLang: "zh-CN", s: {
  "site.name": "明洞未来细胞医院",
  "site.addr": "韩国首尔特别市中区退溪路123号 7楼 明洞未来细胞医院",
  "site.addr.short": "首尔中区退溪路123号 7楼",

  "nav.about": "医院介绍", "nav.services": "诊疗项目", "nav.community": "医院动态", "nav.contact": "咨询·预约",
  "nav.about.intro": "介绍·致辞", "nav.about.greeting": "院长致辞",
  "nav.about.doctor": "医疗团队", "nav.about.values": "诊疗理念",
  "nav.about.location": "交通指南", "nav.about.map": "位置·地图", "nav.about.transport": "公共交通",
  "nav.community.notice": "公告·消息", "nav.community.list": "公告事项", "nav.community.video": "YouTube 视频",
  "nav.community.gallery": "相册", "nav.community.galleryItem": "医院相册",
  "nav.community.faq": "常见问题", "nav.community.faqItem": "FAQ",
  "nav.contact.inquiry": "在线咨询", "nav.contact.form": "咨询表单", "nav.contact.email": "邮件咨询",
  "nav.contact.reserve": "预约就诊", "nav.contact.online": "在线预约申请", "nav.contact.phone": "电话预约 02-776-8768",
  "nav.cta": "预约就诊", "nav.menu": "打开菜单",

  "footer.services": "诊疗项目", "footer.quick": "快捷链接",
  "footer.reserve": "预约就诊", "footer.contact": "在线咨询", "footer.location": "交通指南",
  "footer.notice": "公告·消息", "footer.faq": "常见问题",
  "footer.ceoline": "法人代表 Park Jong-yun · 电话",
  "footer.rights": "明洞未来细胞医院 版权所有。",
  "footer.privacy": "隐私政策",
  "footer.compliance": "本网站内容遵守韩国医疗广告审查标准。",
  "footer.langnote": "本页为方便阅读而提供的译文，以韩文版本为准。",
  "quick.call": "拨打电话", "quick.reserve": "预约就诊",

  "svc.stemcell": "干细胞",
  "svc.stemcell.desc": "以自身的细胞，照护自身的身体。从本人的脂肪与血液中分离并活化负责再生的细胞后，再次应用。",
  "svc.derma": "皮肤科",
  "svc.derma.desc": "我们不只讲会变好的部分。改善多少、能维持多久、有哪些风险，都会如实告知。",
  "svc.plastic": "整形外科",
  "svc.plastic.desc": "显老的原因因人而异。我们从寻找原因开始。",
  "svc.urology": "泌尿科",
  "svc.urology.desc": "这并不罕见，而是多数人都会经历的问题。越是难以启齿，越要从准确的检查开始。",
  "svc.esthetic": "医学美容",
  "svc.esthetic.desc": "治疗一小时，恢复数周。这几周，我们一起看顾。",
  "svc.toenail": "嵌甲（内生趾甲）",
  "svc.toenail.desc": "每走一步都疼的大脚趾，没有必要一直忍。早期也有不拔甲即可好转的情况。",
  "svc.scalp": "头皮护理",
  "svc.scalp.desc": "清理头皮角质与油脂，放松僵硬的头皮，并延伸至面部的护理项目。",
  "svc.lymph": "淋巴护理",
  "svc.lymph.desc": "缓解浮肿 · 循环护理 · 恢复期状态管理。温和地帮助淋巴流动的护理。",
  "svc.worldtour": "世界巡诊",
  "svc.worldtour.desc": "面向韩国国内与海外访客的医疗旅行项目。",
  "svc.quantum": "量子辅助护理",
  "svc.quantum.desc": "细胞也有电池。以光与能量帮助身体自身恢复力的辅助护理项目。",
  "svc.konly.h": "以下详细内容目前仅提供韩文。",
  "page.konly.h": "本页目前仅提供韩文内容。",
  "gal.close": "关闭", "gal.prev": "上一张", "gal.next": "下一张",
  "page.konly.p": "中文审校版本正在准备中。欢迎用中文联系我们，我们会直接为您解答。",
  "svc.konly.p": "该诊疗页面的中文审校版本正在准备中。在此期间，欢迎用中文联系我们，我们会直接为您解答。",

  "home.h1": "从细胞开始，<br>为健康未来而行的诊疗",
  "home.p": "在细胞的时间里重新焕发的，属于您本来的健康与美。<br>以干细胞医学为根基的泌尿医学 · 整形 · 皮肤高端诊疗，<br>明洞未来细胞医院。",
  "home.btn1": "预约就诊", "home.btn2": "查看诊疗项目",
  "home.info.tel": "诊疗咨询", "home.info.loc": "交通指南", "home.info.email": "邮件咨询",
  "home.prog.h2": "诊疗项目介绍",
  "home.prog.p": "从以再生医学为基础的干细胞诊疗，到皮肤、整形与医学美容，请了解各领域的个性化诊疗项目。",
  "home.c.stemcell": "血液（PRP·PRF）、脂肪、骨髓、脐带血干细胞诊疗",
  "home.c.derma": "外泌体、提升、激光焕肤、水光针、填充与肉毒素",
  "home.c.plastic": "眼 · 鼻 · 胸，植发，上下眼睑，提升，女性整形",
  "home.c.urology": "前列腺疾病、男科手术、性功能障碍（跳转至专属网站）",
  "home.c.esthetic": "面部与全身护理，医学按摩",
  "home.c.scalp": "头皮护理 · 嵌甲",
  "home.c.scalp.d": "头皮护理项目与嵌甲治疗",
  "home.c.lymph": "帮助缓解浮肿与循环管理的淋巴护理",
  "home.c.quantum": "量子辅助护理",
  "home.c.quantum.d": "量子辅助护理 · 世界巡诊项目",
  "home.more": "查看详情 →",
  "home.about.h2": "从生命之源——细胞开始的<br>诚实医疗",
  "home.about.p1": "明洞未来细胞医院以再生医学与预防医学为基础，致力于为每一位患者提供贴合其健康状态的精准诊疗。",
  "home.about.p2": "在首尔明洞中心，我们提供干细胞诊疗、皮肤与整形、医学美容以及量子辅助护理等综合医疗服务。",
  "home.about.btn": "了解医院介绍",
  "home.news.h2": "公告 · 消息", "home.news.btn": "查看全部消息",
  "home.news.b1": "公告", "home.news.b2": "通知", "home.news.b3": "消息",
  "home.news.1": "明洞未来细胞医院官网全新上线。",
  "home.news.2": "诊疗时间及预约指南（后续更新）。",
  "home.news.3": "干细胞诊疗项目咨询指南。",
  "home.rsv.h2": "现在就预约咨询",
  "home.rsv.p": "一通电话、一次点击，即可开始与专业医疗团队的咨询。",
  "home.rsv.btn": "在线预约申请",

  "page.reserve.crumb": "首页 > 申请·预约",
  "page.reserve.h1": "预约就诊申请",
  "page.reserve.p": "请留下您希望的时间，我们确认后会与您联系。",
  "page.contact.crumb": "首页 > 在线咨询",
  "page.contact.h1": "在线咨询",
  "page.contact.p": "请留下您的疑问，我们确认后会给您答复。",

  "form.name": "姓名", "form.name.ph": "您的姓名",
  "form.phone": "联系电话", "form.phone.ph": "010-0000-0000",
  "form.email": "电子邮箱", "form.email.ph": "example@email.com",
  "form.date": "希望日期",
  "form.time": "希望时段",
  "form.time.am": "上午", "form.time.pm": "下午", "form.time.any": "均可",
  "form.topic.r": "诊疗项目", "form.topic.c": "咨询类别",
  "form.topic.etc": "其他",
  "form.msg.r": "咨询内容",
  "form.msg.r.ph": "写下症状或想了解的问题，有助于我们提前准备。",
  "form.msg.c": "咨询内容",
  "form.msg.c.ph": "请自由填写您想咨询的内容。",
  "form.note.r": "※ 收到申请后，工作人员将在诊疗时间内致电您留下的号码，为您确认预约。",
  "form.note.c": "※ 收到咨询后，工作人员将在诊疗时间内通过您留下的联系方式答复。",
  "form.submit.r": "提交预约申请", "form.submit.c": "提交咨询",
  "form.urgent1": "如有急事，请致电", "form.urgent2": "。",

  "consent.legend": "个人信息收集·使用同意",
  "consent.req": "[必填]",
  "consent.opt": "[选填]",
  "consent.req.r": "本人同意为预约咨询目的收集与使用个人信息。",
  "consent.req.r.d": "收集项目：姓名、联系电话、希望时间 · 使用目的：确认预约及联系咨询 · 保存期限：3年（您可以拒绝，但拒绝后将无法在线预约。）",
  "consent.req.c": "本人同意为答复咨询目的收集与使用个人信息。",
  "consent.req.c.d": "收集项目：姓名、联系电话、电子邮箱 · 使用目的：答复与指引咨询 · 保存期限：3年（您可以拒绝，但拒绝后将无法在线咨询。）",
  "consent.opt.r": "本人同意收集与使用咨询内容中包含的健康相关信息（敏感信息）。",
  "consent.opt.r.d": "即使不同意也可以提交，此时咨询内容不会被保存，仅接收您的联系方式。",
  "consent.opt.c": "本人同意收集与使用咨询内容中包含的健康相关信息（敏感信息）。",
  "consent.opt.c.d": "即使不同意也可以提交，此时咨询内容不会被保存，仅接收您的联系方式。",
  "consent.link": "查看隐私政策全文",

  "contact.info.tel": "电话咨询", "contact.info.email": "邮件咨询", "contact.info.visit": "到院咨询",

  "msg.name_invalid": "请正确填写姓名。",
  "msg.phone_invalid": "请确认联系电话格式（例：010-0000-0000）。",
  "msg.email_invalid": "请确认电子邮箱地址。",
  "msg.date_invalid": "请确认所选日期。",
  "msg.date_required": "请选择希望日期。",
  "msg.message_required": "请填写咨询内容。",
  "msg.consent_required": "需同意个人信息收集·使用后才能提交。",
  "msg.captcha_failed": "防机器人验证未通过，请稍后再试。",
  "msg.rate_limited": "短时间内提交次数过多。请稍后再试，或直接致电我们。",
  "msg.origin_not_allowed": "无法确认提交来源。请重新打开官网后再试。",
  "msg.generic": "提交过程中出现问题。",
  "msg.failhead": "未能提交。",
  "msg.failtail1": "若问题持续，请致电", "msg.failtail2": "。",
  "msg.sending": "正在提交…",
  "msg.done.r": "预约申请已受理",
  "msg.done.c": "咨询已受理",
  "msg.done.p": "我们确认后会通过您留下的联系方式与您联系。<br>诊疗时间内提交的将于当天回复，其余将于下一个诊疗日回复。",
  "msg.done.tel": "如有急事，"
}},

/* ══════════════════ 日本語 ══════════════════ */
ja: { name: "日本語", short: "日本語", htmlLang: "ja", s: {
  "site.name": "明洞未来セルクリニック",
  "site.addr": "韓国ソウル特別市中区退渓路123、7階 明洞未来セルクリニック",
  "site.addr.short": "ソウル中区退渓路123、7階",

  "nav.about": "クリニック紹介", "nav.services": "診療案内", "nav.community": "お知らせ", "nav.contact": "お問い合わせ・予約",
  "nav.about.intro": "紹介・ごあいさつ", "nav.about.greeting": "ごあいさつ",
  "nav.about.doctor": "医師紹介", "nav.about.values": "診療の考え方",
  "nav.about.location": "アクセス", "nav.about.map": "所在地・地図", "nav.about.transport": "公共交通のご案内",
  "nav.community.notice": "お知らせ", "nav.community.list": "お知らせ一覧", "nav.community.video": "YouTube 動画",
  "nav.community.gallery": "ギャラリー", "nav.community.galleryItem": "院内ギャラリー",
  "nav.community.faq": "よくあるご質問", "nav.community.faqItem": "FAQ",
  "nav.contact.inquiry": "お問い合わせ", "nav.contact.form": "お問い合わせフォーム", "nav.contact.email": "メールでのお問い合わせ",
  "nav.contact.reserve": "診療のご予約", "nav.contact.online": "オンライン予約申込", "nav.contact.phone": "電話予約 02-776-8768",
  "nav.cta": "診療を予約する", "nav.menu": "メニューを開く",

  "footer.services": "診療案内", "footer.quick": "リンク",
  "footer.reserve": "診療のご予約", "footer.contact": "お問い合わせ", "footer.location": "アクセス",
  "footer.notice": "お知らせ", "footer.faq": "よくあるご質問",
  "footer.ceoline": "代表者 Park Jong-yun · Tel",
  "footer.rights": "明洞未来セルクリニック All rights reserved.",
  "footer.privacy": "個人情報保護方針",
  "footer.compliance": "本サイトの内容は韓国の医療広告審査基準を遵守しています。",
  "footer.langnote": "このページは参考のための翻訳です。韓国語版が正文となります。",
  "quick.call": "電話をかける", "quick.reserve": "診療を予約する",

  "svc.stemcell": "幹細胞",
  "svc.stemcell.desc": "ご自身の細胞で、ご自身のからだを。ご本人の脂肪と血液から再生を担う細胞を分離・活性化し、あらためて適用します。",
  "svc.derma": "皮膚科",
  "svc.derma.desc": "良くなることだけをお伝えするのではありません。どの程度、いつまで、どんなリスクがあるかまでご説明します。",
  "svc.plastic": "形成外科",
  "svc.plastic.desc": "老けて見える理由は人それぞれです。まずはその理由を見つけることから始めます。",
  "svc.urology": "泌尿器科",
  "svc.urology.desc": "珍しいことではなく、多くの方が経験することです。話しにくい悩みほど、正確な検査から始めます。",
  "svc.esthetic": "エステティック",
  "svc.esthetic.desc": "施術は一時間、回復は数週間。その数週間をご一緒に見守ります。",
  "svc.toenail": "巻き爪",
  "svc.toenail.desc": "一歩ごとに痛む親指の爪、我慢し続ける理由はありません。初期であれば爪を抜かずに良くなる場合もあります。",
  "svc.scalp": "頭皮ケア",
  "svc.scalp.desc": "頭皮の角質と皮脂を整え、こわばった頭皮をほぐしたうえで、顔まで続けてケアするプログラムです。",
  "svc.lymph": "リンパケア",
  "svc.lymph.desc": "むくみの緩和・循環ケア・回復期のコンディションケア。リンパの流れをやさしく助けるケアです。",
  "svc.worldtour": "ワールドツアー",
  "svc.worldtour.desc": "韓国国内の方にも、海外からお越しの方にも向けたメディカルツアープログラムです。",
  "svc.quantum": "クォンタム量子ケア",
  "svc.quantum.desc": "細胞にもバッテリーがあります。光とエネルギーでからだ本来の回復力を助ける、補助的なケアプログラムです。",
  "svc.konly.h": "以下の詳細は現在、韓国語のみのご提供です。",
  "page.konly.h": "このページは現在、韓国語のみのご提供です。",
  "gal.close": "閉じる", "gal.prev": "前の写真", "gal.next": "次の写真",
  "page.konly.p": "日本語版は監修中です。日本語でお問い合わせいただければ、直接ご回答いたします。",
  "svc.konly.p": "この診療ページの日本語版は監修中です。その間は日本語でお問い合わせいただければ、直接ご回答いたします。",

  "home.h1": "細胞から始める、<br>健やかな未来のための診療",
  "home.p": "細胞の時間のなかで新たに生まれ変わる、あなた本来の健康と美しさ。<br>幹細胞医学に根ざした泌尿器・形成・皮膚のプレミアムケア、<br>明洞未来セルクリニックです。",
  "home.btn1": "診療を予約する", "home.btn2": "診療案内を見る",
  "home.info.tel": "診療のご相談", "home.info.loc": "アクセス", "home.info.email": "メールでのお問い合わせ",
  "home.prog.h2": "診療科目のご案内",
  "home.prog.p": "再生医学に基づく幹細胞ケアから、皮膚・形成・エステティックまで。分野ごとのプログラムをご覧ください。",
  "home.c.stemcell": "血液（PRP・PRF）・脂肪・骨髄・臍帯血の幹細胞ケア",
  "home.c.derma": "エクソソーム、リフティング、レーザートーニング、スキンブースター、フィラー・ボトックス",
  "home.c.plastic": "目・鼻・胸、植毛、上下眼瞼、リフティング、女性形成",
  "home.c.urology": "前立腺疾患、男性手術、性機能障害（専用サイトへ）",
  "home.c.esthetic": "フェイス・全身ケア、メディカルマッサージ",
  "home.c.scalp": "頭皮ケア · 巻き爪",
  "home.c.scalp.d": "頭皮ケアプログラムと巻き爪の治療",
  "home.c.lymph": "むくみの緩和と循環ケアを助けるリンパケア",
  "home.c.quantum": "クォンタム量子ケア",
  "home.c.quantum.d": "クォンタム量子ケア · ワールドツアープログラム",
  "home.more": "詳しく見る →",
  "home.about.h2": "生命の源である細胞から始まる、<br>誠実な医療",
  "home.about.p1": "明洞未来セルクリニックは、再生医学と予防医学を土台に、お一人おひとりの状態に合わせた精密な診療を目指しています。",
  "home.about.p2": "ソウル・明洞の中心で、幹細胞ケア、皮膚・形成、エステティック、クォンタム量子ケアまで、統合的な医療サービスをご提供します。",
  "home.about.btn": "クリニック紹介を見る",
  "home.news.h2": "お知らせ", "home.news.btn": "お知らせ一覧を見る",
  "home.news.b1": "お知らせ", "home.news.b2": "ご案内", "home.news.b3": "ニュース",
  "home.news.1": "明洞未来セルクリニックのホームページを新しく開設しました。",
  "home.news.2": "診療時間および予約のご案内（今後更新予定）。",
  "home.news.3": "幹細胞プログラムのご相談について。",
  "home.rsv.h2": "今すぐご相談のご予約を",
  "home.rsv.p": "お電話一本、クリック一回で、医療スタッフとのご相談が始まります。",
  "home.rsv.btn": "オンライン予約申込",

  "page.reserve.crumb": "HOME > 申込・予約",
  "page.reserve.h1": "診療予約のお申込み",
  "page.reserve.p": "ご希望の日程をお知らせいただければ、確認のうえご連絡いたします。",
  "page.contact.crumb": "HOME > お問い合わせ",
  "page.contact.h1": "お問い合わせ",
  "page.contact.p": "ご不明な点をお寄せください。確認のうえご回答いたします。",

  "form.name": "お名前", "form.name.ph": "お名前",
  "form.phone": "ご連絡先", "form.phone.ph": "010-0000-0000",
  "form.email": "メールアドレス", "form.email.ph": "example@email.com",
  "form.date": "ご希望日",
  "form.time": "ご希望の時間帯",
  "form.time.am": "午前", "form.time.pm": "午後", "form.time.any": "どちらでも",
  "form.topic.r": "診療分野", "form.topic.c": "お問い合わせ分野",
  "form.topic.etc": "その他",
  "form.msg.r": "ご相談内容",
  "form.msg.r.ph": "症状や気になる点をご記入いただくと、ご相談の参考になります。",
  "form.msg.c": "お問い合わせ内容",
  "form.msg.c.ph": "お問い合わせ内容をご自由にご記入ください。",
  "form.note.r": "※ お申込み後、診療時間内に担当者がご記入の連絡先へお電話し、ご予約を確定いたします。",
  "form.note.c": "※ お問い合わせ後、診療時間内に担当者がご記入の連絡先へご回答いたします。",
  "form.submit.r": "予約を申し込む", "form.submit.c": "問い合わせる",
  "form.urgent1": "お急ぎの場合は", "form.urgent2": "までお電話ください。",

  "consent.legend": "個人情報の収集・利用に関する同意",
  "consent.req": "[必須]",
  "consent.opt": "[任意]",
  "consent.req.r": "予約相談のための個人情報の収集・利用に同意します。",
  "consent.req.r.d": "収集項目：お名前、ご連絡先、ご希望日程 · 利用目的：予約確認およびご相談のご連絡 · 保有期間：3年（拒否いただけますが、その場合オンライン予約のお受付ができません。）",
  "consent.req.c": "お問い合わせへの回答のための個人情報の収集・利用に同意します。",
  "consent.req.c.d": "収集項目：お名前、ご連絡先、メールアドレス · 利用目的：お問い合わせへの回答およびご案内 · 保有期間：3年（拒否いただけますが、その場合オンラインでのお受付ができません。）",
  "consent.opt.r": "ご相談内容に含まれる健康関連情報（機微情報）の収集・利用に同意します。",
  "consent.opt.r.d": "同意されなくてもお受付は可能です。その場合、ご相談内容は保存されず、ご連絡先のみお預かりします。",
  "consent.opt.c": "お問い合わせ内容に含まれる健康関連情報（機微情報）の収集・利用に同意します。",
  "consent.opt.c.d": "同意されなくてもお受付は可能です。その場合、お問い合わせ内容は保存されず、ご連絡先のみお預かりします。",
  "consent.link": "個人情報保護方針の全文を見る",

  "contact.info.tel": "お電話でのお問い合わせ", "contact.info.email": "メールでのお問い合わせ", "contact.info.visit": "ご来院でのご相談",

  "msg.name_invalid": "お名前を正しくご入力ください。",
  "msg.phone_invalid": "ご連絡先の形式をご確認ください。（例：010-0000-0000）",
  "msg.email_invalid": "メールアドレスをご確認ください。",
  "msg.date_invalid": "ご希望日をご確認ください。",
  "msg.date_required": "ご希望日をお選びください。",
  "msg.message_required": "お問い合わせ内容をご入力ください。",
  "msg.consent_required": "個人情報の収集・利用にご同意いただくとお受付が可能です。",
  "msg.captcha_failed": "自動入力防止の確認に失敗しました。しばらくしてからもう一度お試しください。",
  "msg.rate_limited": "短時間に複数回お送りいただいています。しばらくしてからお試しいただくか、お電話ください。",
  "msg.origin_not_allowed": "送信元を確認できませんでした。ホームページから改めてアクセスしてください。",
  "msg.generic": "送信中に問題が発生しました。",
  "msg.failhead": "受け付けられませんでした。",
  "msg.failtail1": "同じ問題が続く場合は", "msg.failtail2": "までお電話ください。",
  "msg.sending": "送信中です…",
  "msg.done.r": "ご予約のお申込みを受け付けました",
  "msg.done.c": "お問い合わせを受け付けました",
  "msg.done.p": "確認のうえ、ご記入の連絡先へ担当者よりご連絡いたします。<br>診療時間内のお申込みは当日、それ以降は次の診療日にご連絡いたします。",
  "msg.done.tel": "お急ぎの場合は"
}},

/* ══════════════════ Русский ══════════════════ */
ru: { name: "Русский", short: "RU", htmlLang: "ru", s: {
  "site.name": "Клиника Myeongdong Mirae Cell",
  "site.addr": "Республика Корея, Сеул, Чун-гу, Тхвеге-ро 123, 7 этаж — клиника Myeongdong Mirae Cell",
  "site.addr.short": "Сеул, Чун-гу, Тхвеге-ро 123, 7 этаж",

  "nav.about": "О клинике", "nav.services": "Лечение", "nav.community": "Новости", "nav.contact": "Контакты и запись",
  "nav.about.intro": "О нас · Приветствие", "nav.about.greeting": "Приветствие",
  "nav.about.doctor": "Наш врач", "nav.about.values": "Принципы работы",
  "nav.about.location": "Как добраться", "nav.about.map": "Адрес и карта", "nav.about.transport": "Общественный транспорт",
  "nav.community.notice": "Объявления и новости", "nav.community.list": "Объявления", "nav.community.video": "Видео на YouTube",
  "nav.community.gallery": "Галерея", "nav.community.galleryItem": "Галерея клиники",
  "nav.community.faq": "Частые вопросы", "nav.community.faqItem": "FAQ",
  "nav.contact.inquiry": "Написать нам", "nav.contact.form": "Форма обращения", "nav.contact.email": "Написать на почту",
  "nav.contact.reserve": "Запись на приём", "nav.contact.online": "Онлайн-запись", "nav.contact.phone": "Позвонить 02-776-8768",
  "nav.cta": "Записаться", "nav.menu": "Открыть меню",

  "footer.services": "Лечение", "footer.quick": "Быстрые ссылки",
  "footer.reserve": "Записаться", "footer.contact": "Написать нам", "footer.location": "Как добраться",
  "footer.notice": "Объявления и новости", "footer.faq": "Частые вопросы",
  "footer.ceoline": "Руководитель: Park Jong-yun · Тел.",
  "footer.rights": "Клиника Myeongdong Mirae Cell. Все права защищены.",
  "footer.privacy": "Политика конфиденциальности",
  "footer.compliance": "Содержание сайта соответствует корейским правилам проверки медицинской рекламы.",
  "footer.langnote": "Эта страница — перевод для удобства чтения. Юридическую силу имеет корейская версия.",
  "quick.call": "Позвонить", "quick.reserve": "Записаться",

  "svc.stemcell": "Стволовые клетки",
  "svc.stemcell.desc": "Собственные клетки — для собственного тела. Клетки, отвечающие за регенерацию, выделяют из вашей жировой ткани и крови, активируют и применяют снова.",
  "svc.derma": "Дерматология",
  "svc.derma.desc": "Мы говорим не только об улучшениях. Насколько, как надолго и какие есть риски — обо всём честно.",
  "svc.plastic": "Пластическая хирургия",
  "svc.plastic.desc": "Причины возрастных изменений у каждого свои. Мы начинаем с поиска причины.",
  "svc.urology": "Урология",
  "svc.urology.desc": "Это не редкость — с этим сталкивается большинство. Чем труднее говорить о проблеме, тем важнее начать с точного обследования.",
  "svc.esthetic": "Эстетический уход",
  "svc.esthetic.desc": "Процедура — час, восстановление — недели. Эти недели мы проходим вместе с вами.",
  "svc.toenail": "Вросший ноготь",
  "svc.toenail.desc": "Боль в большом пальце при каждом шаге терпеть не нужно. На ранней стадии улучшение возможно и без удаления ногтя.",
  "svc.scalp": "Уход за кожей головы",
  "svc.scalp.desc": "Программа очищает кожу головы от ороговевших чешуек и избытка себума, снимает напряжение и продолжается уходом за лицом.",
  "svc.lymph": "Лимфодренаж",
  "svc.lymph.desc": "Уменьшение отёчности · уход за циркуляцией · поддержка состояния в период восстановления. Мягкая программа для лимфотока.",
  "svc.worldtour": "World Tour",
  "svc.worldtour.desc": "Программа медицинского тура для гостей из Кореи и из-за рубежа.",
  "svc.quantum": "Квантовый уход",
  "svc.quantum.desc": "У клеток тоже есть «батарейка». Вспомогательная программа, которая с помощью света и энергии поддерживает собственное восстановление организма.",
  "svc.konly.h": "Подробности ниже пока доступны только на корейском.",
  "page.konly.h": "Эта страница пока доступна только на корейском.",
  "gal.close": "Закрыть", "gal.prev": "Предыдущее фото", "gal.next": "Следующее фото",
  "page.konly.p": "Проверенная русская версия готовится. Напишите нам по-русски — мы ответим вам напрямую.",
  "svc.konly.p": "Проверенная русская версия этой страницы готовится. Пока что напишите нам по-русски — мы ответим вам напрямую.",

  "home.h1": "Медицина, начинающаяся с клетки,<br>ради здорового будущего",
  "home.p": "Ваше собственное здоровье и красота, обновлённые во времени клетки.<br>Премиальная помощь в урологии, пластической хирургии и дерматологии,<br>основанная на клеточной медицине — клиника Myeongdong Mirae Cell.",
  "home.btn1": "Записаться на приём", "home.btn2": "Посмотреть направления",
  "home.info.tel": "Консультации", "home.info.loc": "Как добраться", "home.info.email": "Электронная почта",
  "home.prog.h2": "Направления лечения",
  "home.prog.p": "От клеточной медицины на основе регенеративного подхода до дерматологии, пластической хирургии и эстетического ухода — выберите подходящую программу.",
  "home.c.stemcell": "Клеточные программы на основе крови (PRP·PRF), жировой ткани, костного мозга и пуповинной крови",
  "home.c.derma": "Экзосомы, лифтинг, лазерный тонинг, скинбустеры, филлеры и ботулотоксин",
  "home.c.plastic": "Глаза · нос · грудь, пересадка волос, верхняя и нижняя блефаропластика, лифтинг, женская хирургия",
  "home.c.urology": "Заболевания простаты, мужская хирургия, нарушения половой функции (откроется отдельный сайт)",
  "home.c.esthetic": "Уход за лицом и телом, медицинский массаж",
  "home.c.scalp": "Кожа головы · Вросший ноготь",
  "home.c.scalp.d": "Программы ухода за кожей головы и лечение вросшего ногтя",
  "home.c.lymph": "Лимфодренажный уход, помогающий уменьшить отёчность",
  "home.c.quantum": "Квантовый уход",
  "home.c.quantum.d": "Квантовый вспомогательный уход · программа World Tour",
  "home.more": "Подробнее →",
  "home.about.h2": "Честная медицина, которая начинается<br>с источника жизни — клетки",
  "home.about.p1": "Клиника Myeongdong Mirae Cell опирается на регенеративную и профилактическую медицину и стремится подбирать лечение под состояние каждого пациента.",
  "home.about.p2": "В центре сеульского района Мёндон мы объединяем клеточные программы, дерматологию и пластическую хирургию, эстетический и квантовый вспомогательный уход.",
  "home.about.btn": "Подробнее о клинике",
  "home.news.h2": "Объявления · Новости", "home.news.btn": "Все новости",
  "home.news.b1": "Объявление", "home.news.b2": "Информация", "home.news.b3": "Новость",
  "home.news.1": "Открыт новый сайт клиники.",
  "home.news.2": "Часы приёма и порядок записи (будет обновляться).",
  "home.news.3": "Как записаться на консультацию по клеточным программам.",
  "home.rsv.h2": "Запишитесь на консультацию сегодня",
  "home.rsv.p": "Один звонок или один клик — и консультация с нашими врачами начнётся.",
  "home.rsv.btn": "Онлайн-запись",

  "page.reserve.crumb": "ГЛАВНАЯ > Запись",
  "page.reserve.h1": "Запись на приём",
  "page.reserve.p": "Оставьте удобное для вас время — мы перезвоним и подтвердим запись.",
  "page.contact.crumb": "ГЛАВНАЯ > Контакты",
  "page.contact.h1": "Написать нам",
  "page.contact.p": "Оставьте свой вопрос — мы ответим после рассмотрения.",

  "form.name": "Имя", "form.name.ph": "Ваше имя",
  "form.phone": "Телефон", "form.phone.ph": "010-0000-0000",
  "form.email": "Эл. почта", "form.email.ph": "example@email.com",
  "form.date": "Желаемая дата",
  "form.time": "Желаемое время",
  "form.time.am": "Первая половина дня", "form.time.pm": "Вторая половина дня", "form.time.any": "Без разницы",
  "form.topic.r": "Направление", "form.topic.c": "Тема обращения",
  "form.topic.etc": "Другое",
  "form.msg.r": "Сообщение",
  "form.msg.r.ph": "Опишите симптомы или вопросы — это поможет подготовиться к консультации.",
  "form.msg.c": "Текст обращения",
  "form.msg.c.ph": "Напишите ваш вопрос в свободной форме.",
  "form.note.r": "※ После получения заявки сотрудник позвонит по указанному номеру в рабочие часы и подтвердит запись.",
  "form.note.c": "※ После получения обращения сотрудник ответит по указанным контактам в рабочие часы.",
  "form.submit.r": "Отправить заявку", "form.submit.c": "Отправить обращение",
  "form.urgent1": "Если вопрос срочный, позвоните", "form.urgent2": ".",

  "consent.legend": "Согласие на сбор и использование персональных данных",
  "consent.req": "[Обязательно]",
  "consent.opt": "[По желанию]",
  "consent.req.r": "Я согласен(на) на сбор и использование персональных данных для консультации по записи.",
  "consent.req.r.d": "Собираемые данные: имя, телефон, желаемое время · Цель: подтверждение записи и связь · Срок хранения: 3 года (Вы можете отказаться, но тогда онлайн-запись будет невозможна.)",
  "consent.req.c": "Я согласен(на) на сбор и использование персональных данных для ответа на обращение.",
  "consent.req.c.d": "Собираемые данные: имя, телефон, эл. почта · Цель: ответ на обращение и информирование · Срок хранения: 3 года (Вы можете отказаться, но тогда онлайн-обращение будет невозможно.)",
  "consent.opt.r": "Я согласен(на) на сбор и использование сведений о здоровье (особая категория данных), содержащихся в моём сообщении.",
  "consent.opt.r.d": "Заявку можно отправить и без этого согласия: в таком случае текст сообщения не сохраняется, принимаются только контактные данные.",
  "consent.opt.c": "Я согласен(на) на сбор и использование сведений о здоровье (особая категория данных), содержащихся в моём обращении.",
  "consent.opt.c.d": "Обращение можно отправить и без этого согласия: в таком случае текст не сохраняется, принимаются только контактные данные.",
  "consent.link": "Читать политику конфиденциальности полностью",

  "contact.info.tel": "По телефону", "contact.info.email": "По электронной почте", "contact.info.visit": "Очная консультация",

  "msg.name_invalid": "Пожалуйста, укажите имя корректно.",
  "msg.phone_invalid": "Проверьте формат номера телефона (например, 010-0000-0000).",
  "msg.email_invalid": "Проверьте адрес электронной почты.",
  "msg.date_invalid": "Проверьте выбранную дату.",
  "msg.date_required": "Выберите желаемую дату.",
  "msg.message_required": "Введите текст обращения.",
  "msg.consent_required": "Заявка принимается только после согласия на сбор и использование персональных данных.",
  "msg.captcha_failed": "Проверка на автоматический ввод не пройдена. Попробуйте ещё раз через минуту.",
  "msg.rate_limited": "Вы отправили несколько заявок за короткое время. Попробуйте позже или позвоните нам.",
  "msg.origin_not_allowed": "Не удалось подтвердить источник заявки. Откройте сайт заново и повторите.",
  "msg.generic": "При отправке возникла ошибка.",
  "msg.failhead": "Заявка не отправлена.",
  "msg.failtail1": "Если проблема повторяется, позвоните", "msg.failtail2": ".",
  "msg.sending": "Отправляем…",
  "msg.done.r": "Заявка на запись принята",
  "msg.done.c": "Обращение принято",
  "msg.done.p": "Мы проверим её и свяжемся с вами по указанным контактам.<br>Заявки, полученные в рабочие часы, обрабатываются в тот же день, остальные — в ближайший приёмный день.",
  "msg.done.tel": "Если вопрос срочный,"
}}

};
